# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/ubuntu2004"
  config.vm.network "private_network", ip: "192.168.33.11"
  
  config.vm.synced_folder "~/dev", "/home/vagrant/dev"
  config.vm.synced_folder "../configs/.gitconfig", "/home/vagrant/.gitconfig"

  config.vm.provider "virtualbox" do |v|
    v.name = "docker-server"
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.provision "shell", path: "./../installs/install_docker.sh"
  config.vm.provision "shell", path: "./../configs/basic_config.sh"
end
