# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |cfg|
  cfg.vm.box = "ubuntu/focal64"

  cfg.vm.provision  "file", source: "../config-files/local/user-seed.conf",
                    destination: "splunk-files/user-seed.conf"
  cfg.vm.provision  "file", source: "../config-files/local/outputs.conf",
                    destination: "splunk-files/outputs.conf"
  cfg.vm.provision  "file", source: "../config-files/local/deploymentclient.conf",
                    destination: "splunk-files/deploymentclient.conf"
  cfg.vm.provision  "file", source: "../software/splunkforwarder-7.2.4.deb", 
                    destination: "splunkforwarder-7.2.4.deb"

  cfg.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
    v.customize ["modifyvm", :id, "--vrde", "off"]
  end

  cfg.vm.define "london" do |ln|
    ln.vm.hostname = "london-forwarder"
    ln.vm.network :private_network, ip: "192.168.33.16"
  end

  cfg.vm.define "madrid" do |mad|
    mad.vm.hostname = "madrid-forwarder"
    mad.vm.network :private_network, ip: "192.168.33.17"
  end

  cfg.vm.provision :ansible do |ansible|
    ansible.playbook = "/Users/carlos/Vagrant/splunk/provision-files/basic-installs.yml"
  end

  cfg.vm.provision :shell, inline: <<-SHELL
    dpkg -i /home/vagrant/splunkforwarder-7.2.4.deb
    cp /home/vagrant/splunk-files/* /opt/splunkforwarder/etc/system/local
    /opt/splunkforwarder/bin/splunk start --accept-license --answer-yes --no-prompt
    /opt/splunkforwarder/bin/splunk enable boot-start
  SHELL
end
