# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "fedora/28-cloud-base"

  config.vm.provider "virtualbox" do |v|
    v.name = "redhat-8"
    v.memory = 512
    v.cpus = 1
  end
  
end
